version: '3.8'
services:
  newman-runner:
    build: .
    container_name: maven-newman-tests
    # Montamos el proyecto local dentro del contenedor para que use el código y pom actual
    volumes:
      - .:/app
      # Opcional: Montar cache de Maven para acelerar descargas en corridas secuenciales
      # - ~/.m2:/root/.m2
    working_dir: /app
    # Comando por defecto al levantar el servicio (ejecutar tests de postman)
    command: mvn clean test

  # Opcional: Contenedor para servidor interactivo de reporte (descomentar si se desea ver el reporte servido en docker)
  # allure-report-server:
  #   image: frankescalona/allure-server:latest
  #   container_name: allure-tests-report
  #   volumes:
  #     - ./target/allure-results:/app/allure-results
  #   ports:
  #     - "5050:5050"
  #   depends_on:
  #     newman-runner:
  #       condition: service_completed_successfully
