name: Run Tests Maven-Newman

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repo (necesario para Docker build context)
      - name: Checkout code
        uses: actions/checkout@v4

      # Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t maven-newman-tests .

      # Ejecutar pruebas dentro del contenedor
      - name: Run tests
        run: |
          docker run --rm maven-newman-tests